### Enable Cors

OPTIONS {{u}}

### Home
GET {{u}}

### Health
GET {{u}}/health
Accept: application/json

###  Signup
POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email = hirostudent@gmail.com &
password = Hiro*2412412###@##P

### Signin
POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email = hirostudent@gmail.com &
password = Hiro*2412412###@##P

### Me
GET {{u}}/users/me

###  update my profile
PATCH {{u}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiaGlyb0BnbWFpbC5jb20iLCJpYXQiOjE2ODg5Njk3NzQsImV4cCI6MTY4ODk3MzM3NH0.wiYwslhhjB9hZBeTnmArTXybNmVhr4IEtaPp7Bs2A5Q

{
  "firstName": "Tadashi",
  "lastName": "Hamada"
}

#### Users: Delete
#DELETE {{u}}/users

### Book: Get
GET {{u}}/books

### Books: Create
POST {{u}}/books
Content-Type: application/json

{
  "title": "Sample Book 2",
  "writer": "John Doe",
  "coverImage": "https://example.com/sample.jpg",
  "point": 100,
  "tags": ["fiction", "adventure"]
}

> {%
  res = response.body

  client.assert(res.id >= 1, "book is valid")

  client.global.set("bookId",res.id)
%}

### Books: Update
PATCH {{u}}/books/{{bookId}}
Content-Type: application/json

{
  "title": "Sample Book Patched",
  "writer": "John Doe",
  "coverImage": "https://example.com/sample.jpg",
  "point": 100,
  "tags": ["fiction", "adventure"]
}

### Books: Delete
DELETE {{u}}/books/{{bookId}}


